#!/usr/bin/php

<?php

$host = !empty(getenv('HOST')) ? getenv('HOST') : "127.0.0.1";
$port = !empty(getenv('PORT')) ? getenv('PORT') : "3301";

if(!class_exists('Tarantool'))
{
    die('Tarantool extension not install.\n');
}

if(count($argv) == 2 && $argv[1] == 'authconf')
{
    exit('yes');
}

if(count($argv) == 2 && $argv[1] == 'config')
{
    echo("graph_title Uptime Tarantool\n");
    echo("graph_vlabel uptime in days\n");
    echo("graph_category tarantool\n");
    echo("uptime.label uptime\n");
    echo("uptime.draw AREA\n"); 
    exit();
}

$tnt = new Tarantool($host.":".$port);
$tnt->connect();
$stats = $tnt->call('box.info')[0][0]['uptime'];

printf ("uptime.value %.2f\n",$stats/86400);

